### ISSUE TITLE
Vidas

### ISSUE THREAD

**Issue by emiliopedrollo** [emiliopedrollo/battle-type#10]
Na descrição do trabalho:

> O jogador perde a vida quando alguma das palavras alcançar a base do retângulo (ou
o jogador). Caso o jogador tenha pontos ganhos suficientes, o jogo lhe apresenta a
possibilidade de compra de uma nova vida. A primeira vida custa 100 pontos, a
segunda vida custa 200, e vai dobrando de preço. O jogo termina quando o jogador
perde a vida e não tem pontos suficientes para comprar a próxima ou não quer
comprar a próxima.

No Multi Player pode ser implementada uma compra automática representada como forma de barra (contendo 20 vidas por padrão) que decresce quando perde vida e volta a crescer novamente quando o jogador acumula pontos suficientes para comprar nova vida.

**Comment by fapedroso** [comment]
Para a versão multiplayer também é possível utilizar um sistema de "escudos", que começaria em 0% e conforme o jogador elimina naves inimigas, e ganha pontos, ele vai aumentando essa porcentagem. Esses escudos representariam as defesas do jogador contra os impactos das naves de seu adversário. Diferentes classes de naves devem causar diferentes estragos nos escudos dos jogadores. Uma vez que uma quantidade de dano tenha sido causada ao escudo seu custo, por pontos, deve dobrar. Ao final um jogador que tome um dano que supera a capacidade de seu escudo perde o jogo.

**Comment by emiliopedrollo** [comment]
No modo Single Player as vidas podem aparecer na mesma posição dos escudor, mas ao invéz de ser uma representação visual em formato de barra, fica apenas um contador Ex.: `x3` para 3 vidas.
