### ISSUE TITLE
Fases

### ISSUE THREAD

**Issue by emiliopedrollo** [emiliopedrollo/battle-type#6]
Na descrição do trabalho:

> O jogo é composto por fases; a cada fase um certo número de palavras é escolhido
pelo jogo e elas vão descendo desde uma posição aleatória no topo da tela em
direção ao jogador. A fase termina quando todas as palavras da fase forem eliminadas
pelo jogador. Após uma breve pausa, o jogo inicia a fase seguinte. A cada nova fase,
devem aumentar os níveis de dificuldade (tamanho das palavras, número de palavras,
velocidade de queda das palavras, etc.).

Não existe conceito de fases atualmente. A dificuldade é aumentada gradualmente com base no tempo de jogo. 

**Conflito # 1**

Aumento gradativo de dificuldade terá que ser abandonado;

**Conflito # 2**

No modo Multi Player como será feita a condição para se passar de fases? Será a mantida a mesma lógica do Single Player? Como implementar para 2 jogadores? 

Talvez deixar o conceito de fases restrito apenas ao Single Player.

Não ficará legal nem mesmo no Silgle Player a menos que o modo Pitthan esteja ativo.

**Conflito # 3**

Velocidade das naves conflite com implementação atual e está relacionado à issue #5

**Comment by fapedroso** [comment]
O **Conflito # 1** pode ser solucionado atravéz da utilização de intervalos na base de palavras que representariam os níveis, já o aumento de dificuldade pode ser aplicado nos intervalos de cada fase.
